### ISSUE TITLE
Use with default authentication method (gcloud or authentication helpers)

### ISSUE THREAD

**Issue by GregoireW** [sethvargo/oidc-auth-google-cloud#4]
It feels like it is more a discussion than an issue but as there are not enable I open this issue.

This process is a great way to get access token, but google helpers (from docker credentials helpers, library helpers, ... )  will use GOOGLE_APPLICATION_CREDENTIALS or call gcloud to get an access token. 

Is there a way to use this access token in a transparent way with those helpers? (like a GOOGLE_APPLICATION_ACCESS_TOKEN env variable) 

Thank you

**Comment by jonjohnsonjr** [comment]
You should be able to set `GOOGLE_APPLICATION_CREDENTIALS` to an appropriate configuration file as per https://cloud.google.com/iam/docs/access-resources-oidc#generate-automatic

Some tools might need to be updated to support this, e.g. the newest [`docker-credential-gcr` release](https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/tag/v2.1.0) _should_ have a recent enough version of golang.org/x/oauth2/google to work (let me know if it doesn't work as expected).

**Comment by sethvargo** [comment]
Hi @GregoireW - thank you for opening an issue. The ability to pass access tokens to the Cloud SDK and other client libraries via an environment variable/flag is still being developed. As @jonjohnsonjr you can set `GOOGLE_APPLICATION_CREDENTIALS` to a configuration file and gcloud will do the access token dance, but there's no current way to give an access token directly to gcloud.

Let me know if you have further questions!

**Comment by GregoireW** [comment]
@sethvargo @jonjohnsonjr    I think I'm becoming blind as I miss the generate-automatic thing which seems to be promising for my use case.

I try to follow the step, there is some type I think ( or there is option not available yet)

In the gcloud doc there is  https://cloud.google.com/iam/docs/workload-identity-federation#impersonation

The  policy binding is linked to the pool, not the provider, so the readme.MD stating 
`
gcloud iam service-accounts add-iam-policy-binding "my-service-account@${PROJECT_ID}.iam.gserviceaccount.com" \
  --role="roles/iam.workloadIdentityUser" \
  --member="principalSet://iam.googleapis.com/${WORKLOAD_IDENTITY_PROVIDER_ID}/*"
`
is wrong.


Also I have hard time to make thing work with repository. 

As repository are in the format `org/name`,  I'm not sure if it is possible to map directly this key and use a  suffix like `/attribute.repo/my-org/my-repo`

I try to map attribute with `attribute.repo=assertion.repository.extract("/{repo}")`   but no luck. Is it possible to have an example on how to do this mapping ? 

Thank you

**Comment by sethvargo** [comment]
Hi @GregoireW 

I updated the README instructions to be a bit clearer (hopefully). You were right that there was a bug in one of the commands.

> As repository are in the format org/name, I'm not sure if it is possible to map directly this key and use a suffix like /attribute.repo/my-org/my-repo

It's possible - I just verified. However, you could also set an attribute on pool admission (instead of at permission mapping time) using a more complex CEL expression if you'd like.

I have an example in the readme, but it's just `attribute.repository=username/repo`.

**Comment by GregoireW** [comment]
Hello,

I created a PR to add a feature creating GOOGLE_APPLICATION_CREDENTIALS  but I got some issues. As I have multiple and some I'm not sure were they come from, (and @jonjohnsonjr  you write I can let you know if there is issues :D )  I write them all here.

First of all, It is funny but the doc seems to change a lot theses days. Doc I had yesterday are not available today.

- My issue yesterday was with the id_token. I miss read the return status which was 400 and not 403.  I created a PR with some change and on it, I added a control to write an error if `id_token` is asked and you do not give `idTokenAudience`. (so good news, it is working now)

- next, a funny thing:   on the cloud console (and I guess with gcloud command, but I did not test)  you can ask for a json file with a format type `txt` 

![image](https://user-images.githubusercontent.com/24318548/134187858-b361b177-e034-4595-95d9-c44dbbcb4670.png)

It give you a json file with a credential source type `txt`  except.... libraries use `text`... [Go lib](https://cs.opensource.google/go/x/oauth2/+/master:google/internal/externalaccount/basecredentials.go;l=138;drc=2bc19b11175fd0ae72c59c53fa45eff3f93d6a46;bpv=1;bpt=1) and  [java lib](https://github.com/googleapis/google-auth-library-java/blob/9ee0fdea10f74d30166052b09dc70b6528ab9e66/oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java#L141)  for instance, So I guess the file generation need to be updated. I choose to implement "text" in the PR I created.

- Speaking of java library: there is a small issue [here](https://github.com/googleapis/google-auth-library-java/blob/9ee0fdea10f74d30166052b09dc70b6528ab9e66/oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java#L143)  Even if we use `text`, the `subject_token_field_name` attribute is mandatory...  (but not used, I tested with random value, it is ok)

- I plan to use this for pushing artifact to GAR for instance.  
  - gcloud (version 357.0.0, the latest) => ERROR: (gcloud.auth.activate-service-account) The .json key file is not in a valid format.
  - docker-credential-helper (2.1.0) => generic error, (permission denied) even if I use a random file, so I'm not sure what the root cause here
  - java plugin helper :  latest version use the 0.16.2 version of google-oauth library [you can check here](https://search.maven.org/artifact/com.google.cloud.artifactregistry/artifactregistry-maven-wagon/2.1.2/jar)  the source code reference the 1.0.0 [I saw this here](https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/blob/master/artifactregistry-maven-wagon/build.gradle) but the correct version should be 1.1.0. If a new release up to date can be done ...
  - npm: google-artifactregistry-auth use an old google-oauth2 libraries so I guess is was my error (but this one is less critical as the main process push access token in configuration file)
  - (did not tested the others)

**Comment by sethvargo** [comment]
To push to GCR or AR, you need to configure Docker to [use the generated access token](https://cloud.google.com/artifact-registry/docs/docker/authentication#token), for example:

```yaml
jobs:
  run:
    # ...

    # Add "id-token" with the intended permissions.
    permissions:
      id-token: write
      contents: read

    steps:
    - id: 'google-cloud-auth'
      name: 'Authenticate to Google Cloud'
      uses: 'sethvargo/oidc-auth-google-cloud@v0.2.0'
      with:
        token_format: 'access_token'
        workload_identity_provider: '[REPLACE]'
        service_account: '[REPLACE]'

    - id: 'docker-login'
      run: |-
        echo "${{ steps.google-cloud-auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://[REGION]-docker.pkg.dev
```

**Comment by GregoireW** [comment]
for the docker it was what I did to test and there is no problem with that. I just have issue to scale this solution on all my build. It is easier to setup the action and let everything the same in the build.

I answer myself on some issue I raise earlier: 

For gcloud it is OK :  it is not with  `gcloud auth activate-service-account` but with `gcloud auth --cred-file`  we need to register the file ( well that counter intuitive and why ???? ) 

Once gcloud work, the other issue are easier to manage as  the process in library is to use GOOGLE_APPLICATION_CREDENTIALS and if it fails, use gcloud authentication. So even if the librairies are not up to date, there is a warning (json invalid. .)  but in the end, it works. 

On the update part, should I open issue on each project or did you take care of this ? 

Again thank you for this process as it solves one of my biggest issue

**Comment by sethvargo** [comment]
Hi @GregoireW 

We're going to update all the actions once GitHub announces this feature is stable. For now, GitHub is still updating the APIs.

**Comment by fleroux514** [comment]
> You should be able to set `GOOGLE_APPLICATION_CREDENTIALS` to an appropriate configuration file as per https://cloud.google.com/iam/docs/access-resources-oidc#generate-automatic
> 
> Some tools might need to be updated to support this, e.g. the newest [`docker-credential-gcr` release](https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/tag/v2.1.0) _should_ have a recent enough version of golang.org/x/oauth2/google to work (let me know if it doesn't work as expected).


Hi, I had the same question in order to know how to authenticate to the [Google maven artifact registry](https://cloud.google.com/artifact-registry/docs/java/authentication#auth-helper) using the gradle plugin.

The link https://cloud.google.com/iam/docs/access-resources-oidc#generate-automatic now redirects to https://cloud.google.com/iam/docs/configuring-workload-identity-federation#oidc and I can't seem to find the info on how to set `GOOGLE_APPLICATION_CREDENTIALS` to an appropriate configuration file.

Thanks
